---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
spec:
  destination:
    name: 'in-cluster'
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/pburgisser/applicationset-test.git'
    targetRevision: HEAD
  project: default
