apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
spec:
  generators:
    - clusters:
        values:
          registry: "registry.echallens.test.local"
  template:
    metadata:
      name: '{{name}}-monitoring'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/pburgisser/applicationset-test.git
        targetRevision: HEAD
        path: charts/monitoring
        helm:
          values: |
            registry: '{{ values.registry }}'
      destination:
        server: '{{server}}'
        namespace: '{{name}}-monitoring'

      syncPolicy:
        syncOptions:
            - CreateNamespace=true