apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
spec:
  generators:
  - list:
      elements: 
      - cluster: formation
        url: https://1.2.3.4 # faux cluster URLs
      - cluster: test
        url: https://2.4.6.8
      - cluster: production
        url: https://9.8.7.6
      - cluster: production
        url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-monitoring'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{url}}'
        namespace: monitoring